// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Note struct {
	ID        uuid.UUID `json:"note_id"`
	Name      string    `json:"note_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Body      string    `json:"note_body"`
	UserID    uuid.UUID `json:"user_id"`
}

type NoteTeam struct {
	NoteID   uuid.UUID
	TeamID   uuid.UUID
	SharedAt time.Time
}

type RefreshToken struct {
	Token     string       `json:"refresh_token"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type Team struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	TeamName  string
	CreatedBy uuid.UUID
	IsPrivate bool
}

type User struct {
	ID              uuid.UUID `json:"user_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	Email           string    `json:"email"`
	HashedPassword  string    `json:"password"`
	HasNotesPremium bool      `json:"has_premium"`
}

type UserTeam struct {
	UserID   uuid.UUID
	TeamID   uuid.UUID
	Role     string
	JoinedAt time.Time
}
