// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: groups.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addToTeam = `-- name: AddToTeam :exec
INSERT INTO user_teams (user_id, team_id, role, joined_at)
VALUES (
    $1,
    $2,
    $3,
    NOW()
)
`

type AddToTeamParams struct {
	UserID uuid.UUID
	TeamID uuid.UUID
	Role   string
}

func (q *Queries) AddToTeam(ctx context.Context, arg AddToTeamParams) error {
	_, err := q.db.ExecContext(ctx, addToTeam, arg.UserID, arg.TeamID, arg.Role)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getAllGroups = `-- name: GetAllGroups :many
SELECT id, created_at, updated_at, team_name, created_by, is_private FROM teams ORDER BY created_at ASC
`

func (q *Queries) GetAllGroups(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamName,
			&i.CreatedBy,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupById = `-- name: GetGroupById :one
SELECT id, created_at, updated_at, team_name, created_by, is_private FROM teams WHERE id = $1
`

func (q *Queries) GetGroupById(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRowContext(ctx, getGroupById, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamName,
		&i.CreatedBy,
		&i.IsPrivate,
	)
	return i, err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT id, created_at, updated_at, team_name, created_by, is_private FROM teams WHERE id = $1
`

func (q *Queries) GetTeamMembers(ctx context.Context, id uuid.UUID) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getTeamMembers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamName,
			&i.CreatedBy,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newGroup = `-- name: NewGroup :exec
INSERT INTO teams (id, created_at, updated_at, team_name, created_by, is_private)
VALUES(
    gen_random_uuid (),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
`

type NewGroupParams struct {
	TeamName  string
	CreatedBy uuid.UUID
	IsPrivate bool
}

func (q *Queries) NewGroup(ctx context.Context, arg NewGroupParams) error {
	_, err := q.db.ExecContext(ctx, newGroup, arg.TeamName, arg.CreatedBy, arg.IsPrivate)
	return err
}

const removeUser = `-- name: RemoveUser :exec
DELETE FROM user_teams WHERE user_id = $1
`

func (q *Queries) RemoveUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeUser, userID)
	return err
}
