// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Note struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.UUID
}

type NoteTeam struct {
	NoteID   uuid.UUID
	TeamID   uuid.UUID
	SharedAt time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Team struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	TeamName  string
	CreatedBy uuid.UUID
	IsPrivate bool
}

type User struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	HashedPassword  string
	HasNotesPremium bool
}

type UserTeam struct {
	UserID   uuid.UUID
	TeamID   uuid.UUID
	Role     string
	JoinedAt time.Time
}
